### ISSUE TITLE
Tuned Model interface doesnt have class_weights

### ISSUE THREAD

**Issue by vishalhedgevantage** [JuliaAI/MLJTuning.jl#134]
The TunedModel interface supports parameter - weights but not class_weights.
For classification problems with highly imbalanced classes, we need tuned model measures working with class weights.

**Comment by OkonSamuel** [comment]
Hello @vishalhedgevantage another approach to solving classification on highly imbalanced dataset is to predict based on a threshold. MLJ offers a wrapper model called `BinaryThreshholdPredictor` that does this.
Just type 
```julia
julia> using MLJ

julia> ?BinaryThreshholdPredictor`  
```
for more info.

**Comment by ablaom** [comment]
@vishalhedgevantage Thanks for flagging this good suggestion.
