### ISSUE TITLE
Scores versus losses being addressed properly in TreeParzen?

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJTuning.jl#136]
That is, do we make sure we are getting the sign correct.

**Comment by lnguyenPHI** [comment]
TreeParzen indeed [doesn't consider the measurement orientation](https://github.com/IQVIA-ML/TreeParzen.jl/blob/900146bb003d4a1afd462908dce7a07e5bfee8b3/src/MLJTreeParzen.jl#L207-L215) when making suggestions. The fix should be as simple as multiplying by -1 for score measures. I'll submit a PR later today!

**Comment by ablaom** [comment]
Please copy me into the PR, thanks.

**Comment by ablaom** [comment]
@lhnguyen-vn We can close this, right?
