### ISSUE TITLE
Broken link (404) for each dependent link of the site https://alan-turing-institute.github.io

### ISSUE THREAD

**Issue by caesquerre** [JuliaAI/MLJTuning.jl#217]
Hi,
I found 404 error code for each link dependent of https://alan-turing-institute.github.io site. e.g. 

How do I implement a new tuning strategy?
This document assumes familiarity with the [Evaluating Model Performance](https://alan-turing-institute.github.io/MLJ.jl/dev/evaluating_model_performance/) and [Performance Measures](https://alan-turing-institute.github.io/MLJ.jl/dev/performance_measures/) sections of the MLJ manual. Tuning itself, from the user's perspective, is described in [Tuning Models](https://alan-turing-institute.github.io/MLJ.jl/dev/tuning_models/).

It will be great to have update links to those resources.

Thanks,

**Comment by ablaom** [comment]
Thanks for posting. The manual recently moved to here: https://juliaai.github.io/MLJ.jl/dev/ following the transfer of ownership of MLJ.jl.

**Comment by ablaom** [comment]
Corrected on dev, the default branch.
